[package]
name = "bogobarf"
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
edition = "2018"

[dependencies]

bytes = "0.4.12"
futures = "0.1.27"
log = "0.4.6"
serde = { version = "1.0.91", features = ["derive" ] }
serde_cbor = "0.9.0"
tokio = "0.1.20"
