[package]
name = "bogobarf_cli"
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
edition = "2018"

[dependencies]

bogobarf = { path = "../bogobarf" }

clap = "2"
log = "0.4"
simplelog = "0.5.3"
tokio = { version = "0.3", features = ["full"] }
futures = "0.3"
